Repository SuperuserLabs/thankful, pull requests merged in 2018-07, with the labels that each got.

#129 Size reduction
  .babelrc
  .gitignore
  package-lock.json
  package.json
  src/content_scripts/content_youtube.js
  src/dashboard/dashboard.js
  src/dashboard/dashboard.pug
  src/dashboard/route.js
  src/dashboard/store/modules/metamask.js
  src/lib/db.js
  src/lib/donate.js
  src/popup/popup.js
  src/popup/popup.pug
  src/popup/popup.vue
  webpack.config.js
Labels: improves: tech debt, priority: high

#131 Update version to 0.5.1
  dist/manifest.json
  package.json
Labels: priority: high

#127 Donation reminders
  package-lock.json
  src/background/background.js
  src/dashboard/store/modules/metamask.js
  src/lib/reminders.js
  src/lib/tabs.js
  src/popup/popup.vue
Labels: improves: retention, priority: high, size: medium, type: enhancement
